### ISSUE TITLE
你好!!我遇到無法調整螢幕亮度的問題了

### ISSUE THREAD

**Issue by yendi1123** [3374575857/i5-4590-B85M-gt730-hackintosh#1]
你好!!我遇到無法調整螢幕亮度的問題了，請問大大有這個問題嗎?如何解決？

**Comment by 3374575857** [comment]
你好 我的桌機剛找了下沒看到螢幕亮度設定的地方，抱歉幫不上你的忙。

**Comment by yendi1123** [comment]
請問是驅動沒起來才沒有螢幕亮度調整嗎!?

**Comment by 3374575857** [comment]
[憲武大大oc部件](https://github.com/daliansky/OC-little/tree/master/05-%E6%B3%A8%E5%85%A5%E8%AE%BE%E5%A4%87/05-2-PNLF%E6%B3%A8%E5%85%A5%E6%96%B9%E6%B3%95)
供你參考看看

**Comment by yendi1123** [comment]
> [憲武大大oc部件](https://github.com/daliansky/OC-little/tree/master/05-%E6%B3%A8%E5%85%A5%E8%AE%BE%E5%A4%87/05-2-PNLF%E6%B3%A8%E5%85%A5%E6%96%B9%E6%B3%95)
> 供你參考看看

感謝你的分享

**Comment by 3374575857** [comment]
我找到了[這個](https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/troubleshooting.html#no-volumebrightness-control-on-external-monitors)
應該是你的問題需要的
安裝[這個](https://github.com/the0neyouseek/MonitorControl/releases)就可以控制螢幕的亮度了 
我在os10.15.4 實測有效

**Comment by yendi1123** [comment]
請問有計畫更新這個ＥＦＩ檔嗎？最近氣運不好 改config都會開不了機

**Comment by 3374575857** [comment]
我的efi已經更新opencore0.5.8了 如果你的硬體跟我一模一樣修改蘋果三碼直接套用就行了，如果跟我不一樣建議參考國外的[教學](https://dortania.github.io/OpenCore-Desktop-Guide/)一般來說一步一步照著做不用2個小時就能配置完了。

**Comment by yendi1123** [comment]
感謝你喔！！

**Comment by yendi1123** [comment]
請問你的三碼是用ＯＣＣ生成的嗎!?我到現在還沒成功過:(

**Comment by 3374575857** [comment]
之前使用clover configurator 生成的
