### ISSUE TITLE
求助：無法成功載入OSX的安裝過程

### ISSUE THREAD

**Issue by ahkui** [3374575857/i5-4590-B85M-gt730-hackintosh#3]
我無法進入安裝過程 

載入過程卡在這

**Comment by ahkui** [comment]
![image](https://user-images.githubusercontent.com/14049597/85205053-2ef5c800-b34b-11ea-9c30-12ef3e0f126a.png)

**Comment by ahkui** [comment]
[opencore-2020-06-20-161837.txt](https://github.com/3374575857/i5-4590-B85M-gt730-hackintosh/files/4808197/opencore-2020-06-20-161837.txt)

**Comment by 3374575857** [comment]
能不能提供下你電腦的配置 還有 系統的版本？

**Comment by 3374575857** [comment]
https://www.reddit.com/r/hackintosh/comments/g0ytm0/comment/fpt28wq

參考看看是不是這個問題

**Comment by ahkui** [comment]
這是我的配置

Motherboard: Asus B85m-G
CPU: i5 4440
GPU: 內顯
RAM: 32G
Lan card: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller

**Comment by 3374575857** [comment]
https://www.reddit.com/r/hackintosh/comments/g7rqt1/if_youre_stuck_at_endrandomseed_or/

這個參考看看 看了你的日誌跟這篇文章提的內容相似

同樣都是安裝系統 同樣的錯誤訊息` [EB|#LOG:EXITBS:START]`

**Comment by 3374575857** [comment]
https://dortania.github.io/OpenCore-Desktop-Guide/troubleshooting/troubleshooting.html#stuck-on-eblogexitbsstart

這裡有詳細的解說
禁用這個值`RebuildAppleMemoryMap`試試看

**Comment by ahkui** [comment]
好的 我試試看 我的安裝的系統是 10.15.5

**Comment by ahkui** [comment]
[opencore-2020-06-21-134558.txt](https://github.com/3374575857/i5-4590-B85M-gt730-hackintosh/files/4809554/opencore-2020-06-21-134558.txt)

我試過了 結果還是一樣進不去 這個是剛產出的LOG

**Comment by 3374575857** [comment]
啟用這兩個試試看
`AppleXcpmCfgLock`  `AppleCpuPmCfgLock`
看最後的日誌感覺跟原本的一樣

**Comment by ahkui** [comment]
這是這一次的結果

[opencore-2020-06-21-135823.txt](https://github.com/3374575857/i5-4590-B85M-gt730-hackintosh/files/4809592/opencore-2020-06-21-135823.txt)
[config.txt](https://github.com/3374575857/i5-4590-B85M-gt730-hackintosh/files/4809593/config.txt)

![IMG_6855](https://user-images.githubusercontent.com/14049597/85226961-c707b600-b40c-11ea-97bf-0e05ab6ea67e.jpg)

**Comment by ahkui** [comment]
這兩個  `AppleXcpmCfgLock` `AppleCpuPmCfgLock` 也有設成 `True`  了

另外 BIOS 的 CFG Lock 也 disable 了

**Comment by 3374575857** [comment]
我也不知道啥問題
你看看你的bios是不是最新版的 我使用最新版的沒這問題

如果 CFG Lock disable 了,這兩個 AppleXcpmCfgLock AppleCpuPmCfgLock false就行了

再不行你拿opencore 最新版的重新配置看看或者拿0.5.6版本的配置看看， 看reddit上說的 好像是0.5.7 0.5.8才有的問題

**Comment by ahkui** [comment]
BIOS 和 opencore 都是最新版

**Comment by 3374575857** [comment]
https://send.firefox.com/download/4363cc56291a0ac3/#CouL27zA4cgnZ9vVdWYi6w

這個我當初0.5.5版本的efi 試試看能不能用

**Comment by ahkui** [comment]
OSX 的版本需要降到 10.15.3 嗎？

**Comment by 3374575857** [comment]
應該不用

**Comment by ahkui** [comment]
需要降版本喔 0.5.5 沒辦法裝 10.15.4/10.15.5

**Comment by 3374575857** [comment]
這次報了什麼錯？

**Comment by ahkui** [comment]
0.5.5 的直接說系統版本不支援

**Comment by ahkui** [comment]
我先載系統 網速有點慢

**Comment by ahkui** [comment]
折騰了一會發現是 iGPU 的設定問題 
目前這個是能夠成功載入到安裝程序
[Asus-B85m-G-OpenCore-Hackintosh](https://github.com/ahkui/Asus-B85m-G-OpenCore-Hackintosh)

晚點換SSD來安裝

感謝您的協助 之後應該會買一張RX580直接插上去
